create table StateMaster(
StateId     number GENERATED BY DEFAULT AS IDENTITY,
StateCode   varchar2(5),
StateName   varchar2(5),
PRIMARY KEY(StateId)
);

Insert into StateMaster(StateCode, StateName) values('DEL', 'Delhi');

create table VaccineMaster(
VaccineId     number GENERATED BY DEFAULT AS IDENTITY,
VaccineCode   varchar2(5),
VaccineName   varchar2(15),
PRIMARY KEY(VaccineId)
);
Insert into VaccineMaster(VaccineCode, VaccineName) values ('ASTR','Astra Zenca');

create table BranchMaster(
BranchId           number GENERATED BY DEFAULT AS IDENTITY,
BranchCode         varchar2(10),
BranchName         varchar2(20),
BranchAddress      varchar2(20),
BranchCity         varchar2(10),
BranchStateCode    varchar2(5),
VaccineId number,
PRIMARY KEY(BranchId),
foreign key (BranchStateCode) references StateMaster(StateCode),
foreign key (VaccineId) references VaccineMaster(VaccineId)

);

Insert into BranchMaster(BranchCode, BranchName, BranchAddress, BranchCity, BranchStateCode, vaccineId) values ('FORT','Fortis Hospital','New Delhi','Delhi','DEL',1);
Insert into BranchMaster(BranchCode, BranchName, BranchAddress, BranchCity, BranchStateCode, vaccineId) values ('ROCK','Rockland Hospital','New Delhi','Delhi','DEL',1);


create table TimeSlotMaster(
TimeSlotId number GENERATED BY DEFAULT AS IDENTITY,
StartTime  varchar2(12),
EndTime    varchar2(12),
PRIMARY KEY(TimeSlotId)
);

Insert into TimeSlotMaster(StartTime, EndTime) values ('10:00 AM','10:15 AM');
Insert into TimeSlotMaster(StartTime, EndTime) values ('01:00 PM','01:15 PM');

create table VaccineBranchMaster(
MappingId        number GENERATED BY DEFAULT AS IDENTITY,
BranchCode       varchar2(10),
VaccineId        number,
AvailabiltyCount number,
TimeSlotId       number,
Primary key(MappingId),
foreign key (BranchCode) references BranchMaster(BranchCode),
foreign key (VaccineId) references VaccineMaster(VaccineId),
foreign key (TimeSlotId) references TimeSlotMaster(TimeSlotId)
);

Insert into VaccineBranchMaster(BranchCode, VaccineId, AvailabiltyCount, TimeSlotId) values('FORT', 1, 50, 1);
Insert into VaccineBranchMaster(BranchCode, VaccineId, AvailabiltyCount, TimeSlotId) values('ROCK', 1, 20, 2);

create table PaymentDetails(
ModeID 			number GENERATED BY DEFAULT AS IDENTITY,
ModeName        varchar2(10),
ModeDetails     varchar2(40),
Primary key(ModeID)
);

Insert into PaymentDetails(ModeName, ModeDetails) values('Cash','Cash Payment');
Insert into PaymentDetails(ModeName, ModeDetails) values('Credit','Payment through Credit Card');


create table HosipltalVaccinationDetals(
TransID             number GENERATED BY DEFAULT AS IDENTITY,
BranchCode          varchar2(10),
VaccineId           number,
VaccinationDate         date,
PaitentName         varchar2(20),
PaitentAddress      varchar2(50),
PaitentEmail        varchar2(30),
PayModeid           number,
PayModeDetails      varchar2(40),
Amount              number,
TimeSlotId          number,
ConfirmMailSent     varchar2(2),
IsVaccineApplied    varchar2(2),
BookingBy           varchar2(20),
BookingTime         timestamp,
Primary key(TransID),
foreign key (BranchCode) references BranchMaster(BranchCode),
foreign key (VaccineId) references VaccineMaster(VaccineId),
foreign key (TimeSlotId) references TimeSlotMaster(TimeSlotId),
foreign key (PayModeid) references PaymentDetails(ModeID)
);

Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('ROCK',1,'2021-01-15','Chitranjan Das1','Test,test,New Delhi','abc@gmail.com',1,'Credit - XXXXXX',2500,1,'Y','Y','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));
Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('ROCK',1,'2021-01-15','Chitranjan Das2','Test,test,New Delhi','abc@gmail.com',1,'Credit - XXXXXX',2500,1,'N','Y','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));
Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('ROCK',1,'2021-01-15','Chitranjan Das3','Test,test,New Delhi','abc@gmail.com',1,'Credit - XXXXXX',2500,1,'Y','N','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));

Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('FORT',1,'2021-01-15','Chitranjan Das4','Test,test,New Delhi','abc1@gmail.com',1,'Cash',2500,1,'Y','N','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));
Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('FORT',1,'2021-01-15','Chitranjan Das5','Test,test,New Delhi','abc23@gmail.com',1,'Credit - XXXXXX',2500,1,'N','N','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));
Insert into HosipltalVaccinationDetals(BranchCode,VaccineId,VaccinationDate,PaitentName,PaitentAddress,PaitentEmail,PayModeid,PayModeDetails,Amount,TimeSlotId,ConfirmMailSent,IsVaccineApplied,BookingBy,BookingTime) values('FORT',1,'2021-01-15','Chitranjan Das6','Test,test,New Delhi','abc3@gmail.com',1,'Credit - XXXXXX',2500,1,'Y','Y','Chitranjan',parsedatetime('2021-01-10 13:10:11', 'yyyy-mm-dd hh:mm:ss'));

create table EmailDetails(
Id             number GENERATED BY DEFAULT AS IDENTITY,
TransID        number,
emailAddess    varchar2(30),
MailSubject    varchar2(100),
MailContent    varchar2(100),
Primary key(Id),
foreign key (TransID) references HosipltalVaccinationDetals(TransID)
);

insert into EmailDetails (TransID,emailAddess, MailSubject, MailContent) values (1, 'abc@gmail.com','Vaccine applied', 'Congrats! Vaccine applied to you!');